######################################################################
# Automatically generated by qmake (3.1) Fri Aug 9 22:26:32 2019
######################################################################

QT += testlib \
      core \
      opengl \ 
	  gui \
	  widgets \
	  concurrent \ # Mutexes/multithreading
	  openglextensions \
	  multimedia \
	  gamepad \ # Controller support
	  network # TCP/IP
	  
TEMPLATE = app
TARGET = unit_tests
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input

HEADERS += src/test_base.h \
           src/test_GbDagNode.h \
		   src/test_GbQuaternion.h \
           src/test_GbMatrix.h \
		   src/test_GbVector.h\
		   src/test_GbParallelization.h

SOURCES += src/main.cpp \
           src/test_GbDagNode.cpp \
		   src/test_GbQuaternion.cpp \
           src/test_GbMatrix.cpp \
		   src/test_GbVector.cpp\
		   src/test_GbParallelization.cpp

# Load in library files for main project
include(unit_tests.pri)

# Set general configuration options /////////////////////////////////////////////////
CONFIG += c++latest # Add support for c++17.
CONFIG += qt thread # console 
CONFIG += debug_and_release # Creates additional debug and release folders, but need it for debug

CONFIG(debug, debug|release){
    DESTDIR = ../app/debug
	DEFINES += DEBUG_MODE
} else {
    DESTDIR = ../app/release
}

# Do not display debug output in release mode
CONFIG(debug, debug|release) : CONFIG += debug_info
CONFIG(release, debug|release) : DEFINES += QT_NO_DEBUG_OUTPUT

CONFIG += no_lflags_merge # Ensures that the list of libraries stored in the LIBS variable is not reduced to a list of unique values before it is used.
# CONFIG += CONSOLE # makes this a console application
CONFIG += flat # flattens file hierarchy, subtract if this is not desired

# Defines //////////////////////////////////////////////////////////////////////////
DEFINES += _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64 QT_DLL QT_OPENGL_LIB QT_OPENGLEXTENSIONS_LIB QT_WIDGETS_LIB
DEFINES += DEVELOP_MODE
DEFINES += PYTHONQT_STATIC_LIB
DEFINES += LINALG_USE_EIGEN
INCLUDEPATH += ./qt_generated \
    . \
    ./qt_generated/$(ConfigurationName) 
	
LIBS += -lopengl32 \
    -lglu32 
DEPENDPATH += .


# Add Libraries ////////////////////////////////////////////////////////////////////
# Include PythonQt and required libraries
LIBS += -L$$(PYTHON_LIB)/ -lpython$$(PYTHON_VERSION) # L"PATH" adds PATH to library search directory list, and -lName loads library Name during linking

include ( ../../third_party/PythonQt/build/common.prf )  
include ( ../../third_party/PythonQt/build/PythonQt.prf )  

# Eigen
INCLUDEPATH += C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/src/third_party/eigen \
			   C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/src/third_party/eigen/Eigen

# ASSIMP
INCLUDEPATH += ../../third_party/assimp/assimp-5.0.0/include
INCLUDEPATH += ../../third_party/assimp/assimp-5.0.0/build/include
CONFIG(debug, debug|release) : LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/assimp" -lassimp_d
CONFIG(release, debug|release) : LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/assimp" -lassimp

# PhysX
INCLUDEPATH += ../../../PhysX/physx/include \
			   ../../../PhysX/pxshared/include
CONFIG(debug, debug|release) { 
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysX_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysXCharacterKinematic_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysXCommon_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysXCooking_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysXExtensions_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysXFoundation_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysXPvdSDK_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/debug" -lPhysXVehicle_static_32
}
CONFIG(release, debug|release) { 
	# Always needed
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysXCommon_static_32
	
	# Always needed
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysX_static_32
	
	# Always needed
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysXFoundation_static_32
	
	# To cook geometry data on the fly
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysXCooking_static_32
	
	# Other
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysXCharacterKinematic_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysXExtensions_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysXPvdSDK_static_32
	LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/physx/release" -lPhysXVehicle_static_32
}
			
# Freetype			
INCLUDEPATH +=  ../../third_party/freetype-2.10.1/include
CONFIG(debug, debug|release) : LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/freetype/debug" -lfreetype
CONFIG(release, debug|release) : LIBS += -L"C:/Users/dante/Documents/Projects/grand-blue-engine/grand_blue/lib/freetype/debug" -lfreetype