# -*- coding: utf-8 -*-
"""
Generates the .pri file for loading in all source code present in project 
repo

Created on Thu Aug  1 19:28:10 2019

@author: dante

See: https://www.toptal.com/qt/vital-guide-qmake
"""

import os
import sys

def create_file_list_str(name: str, file_paths: str):
    file_paths.sort()
    file_list_str = ""
    file_list_str += "{} += ".format(name)
    
    for i, fp in enumerate(file_paths):
        file_list_str += fp
        if i != len(file_paths) - 1:
            file_list_str += " \\"
        file_list_str += " \n \t"
    
    file_list_str += "\n"
    return file_list_str

print(sys.argv)
project_dir = sys.argv[1]
dest_dir = sys.argv[2]
dest_pri_name = sys.argv[3]

extensions = ["h", "cpp", "ui", "qrc"]
file_header = "# ----------------------------------------------------\n" + \
         "# This file was generated by generate_source_pri.py\n" + \
         "# ----------------------------------------------------\n"
    
headers = []
sources = []
forms = []
resources = []

for dir_name, subdir_list, file_list in os.walk(project_dir):
    dir_path = os.path.abspath(dir_name).replace("\\", "/")

    if "qt_generated" in dir_name:
        continue

    print("Found directory: {}".format(dir_path))
    for file_name in file_list:
        extension = file_name.split(".")[-1]
        full_name = dir_path + "/" + file_name
        
        if extension not in extensions:
            continue
        elif "eigen/" in dir_path and "eigen/Eigen" not in dir_path:
            # Avoid extra eigen directories
            continue
        elif "main.cpp" in file_name:
            # avoid duplicating main.cpp from main project
	        continue
        print("\t{}".format(file_name))

        if extension == "h":
            headers.append(full_name)
        elif extension == "cpp":
            sources.append(full_name)
        elif extension == "qrc":
            resources.append(full_name)
        elif extension == "ui":
            forms.append(full_name)
            
out_pri_file = os.path.join(dest_dir, dest_pri_name).replace("\\", "/")
header_str = create_file_list_str("HEADERS", headers)
sources_str = create_file_list_str("SOURCES", sources)
forms_str = create_file_list_str("FORMS", forms)
resources_str = create_file_list_str("RESOURCES", resources)
# include_path_str = 'INCLUDEPATH += "../grand_blue"'

with open(out_pri_file, "w") as f:
    f.write(file_header)
    f.write("\n")
    
    f.write(header_str)
    f.write(sources_str)
    f.write(forms_str)
    f.write(resources_str)
	
    # f.write(include_path_str)
    
print("Done generating " + out_pri_file)